using AutoMapper;
using ERPAccounting.Application.DTOs.Documents;
using ERPAccounting.Domain.Entities;

namespace ERPAccounting.Application.Mapping;

/// <summary>
/// AutoMapper profile responsible for translating document aggregates to DTOs and vice versa.
/// </summary>
public class DocumentMappingProfile : Profile
{
    public DocumentMappingProfile()
    {
        // Document Entity -> DocumentDto (for reading)
        CreateMap<Document, DocumentDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.IDDokument))
            .ForMember(dest => dest.DocumentNumber, opt => opt.MapFrom(src => src.BrojDokumenta))
            .ForMember(dest => dest.DocumentDate, opt => opt.MapFrom(src => src.Datum))
            .ForMember(dest => dest.PartnerId, opt => opt.MapFrom(src => src.IDPartner))
            .ForMember(dest => dest.OrganizationalUnitId, opt => opt.MapFrom(src => src.IDOrganizacionaJedinica))
            .ForMember(dest => dest.ReferentDocumentId, opt => opt.MapFrom(src => src.IDReferentniDokument))
            .ForMember(dest => dest.DependentCostsNet, opt => opt.MapFrom(src => src.ZavisniTroskoviBezPDVa))
            .ForMember(dest => dest.DependentCostsVat, opt => opt.MapFrom(src => src.ZavisniTroskoviPDV))
            .ForMember(dest => dest.Note, opt => opt.MapFrom(src => src.Napomena))
            .ForMember(dest => dest.Processed, opt => opt.MapFrom(src => src.ObradjenDokument))
            .ForMember(dest => dest.Posted, opt => opt.MapFrom(src => src.ProknjizenDokument))
            .ForMember(dest => dest.ETag, opt => opt.MapFrom(src => src.DokumentTimeStamp == null ? string.Empty : Convert.ToBase64String(src.DokumentTimeStamp)));

        // CreateDocumentDto -> Document Entity (for creation)
        CreateMap<CreateDocumentDto, Document>()
            // Primary key auto-generated
            .ForMember(dest => dest.IDDokument, opt => opt.Ignore())
            
            // ✅ REQUIRED FIELDS from form
            .ForMember(dest => dest.IDVrstaDokumenta, opt => opt.MapFrom(src => src.DocumentTypeCode))
            .ForMember(dest => dest.BrojDokumenta, opt => opt.MapFrom(src => src.DocumentNumber))
            .ForMember(dest => dest.Datum, opt => opt.MapFrom(src => src.DocumentDate))
            .ForMember(dest => dest.IDOrganizacionaJedinica, opt => opt.MapFrom(src => src.OrganizationalUnitId))
            
            // ✅ OPTIONAL FIELDS from form
            .ForMember(dest => dest.IDPartner, opt => opt.MapFrom(src => src.PartnerId))
            .ForMember(dest => dest.IDRadnik, opt => opt.MapFrom(src => src.ReferentId))  // ✅ Fixed: was IDReferentniDokument
            .ForMember(dest => dest.IDNacinOporezivanja, opt => opt.MapFrom(src => src.TaxationMethodId))
            .ForMember(dest => dest.DatumDPO, opt => opt.MapFrom(src => src.DueDate))
            .ForMember(dest => dest.DatumValute, opt => opt.MapFrom(src => src.CurrencyDate))
            .ForMember(dest => dest.PartnerBrojDokumenta, opt => opt.MapFrom(src => src.PartnerDocumentNumber))
            .ForMember(dest => dest.PartnerDatumDokumenta, opt => opt.MapFrom(src => src.PartnerDocumentDate))
            .ForMember(dest => dest.IDStatus, opt => opt.MapFrom(src => src.StatusId))
            .ForMember(dest => dest.IDValuta, opt => opt.MapFrom(src => src.CurrencyId))
            .ForMember(dest => dest.KursValute, opt => opt.MapFrom(src => src.ExchangeRate ?? 1.0m))  // Default 1.0
            .ForMember(dest => dest.Napomena, opt => opt.MapFrom(src => src.Notes))
            
            // ✅ BACKEND-MANAGED FIELDS (not from form)
            .ForMember(dest => dest.ObradjenDokument, opt => opt.MapFrom(src => false))  // Default false
            .ForMember(dest => dest.ProknjizenDokument, opt => opt.MapFrom(src => false))  // Default false
            .ForMember(dest => dest.ZavisniTroskoviBezPDVa, opt => opt.MapFrom(src => 0))  // Default 0
            .ForMember(dest => dest.ZavisniTroskoviPDV, opt => opt.MapFrom(src => 0))  // Default 0
            
            // 🚫 IGNORED FIELDS (system-generated or not applicable)
            .ForMember(dest => dest.IDReferentniDokument, opt => opt.Ignore())  // Different from IDRadnik!
            .ForMember(dest => dest.DokumentTimeStamp, opt => opt.Ignore())  // Auto-generated by SQL
            .ForMember(dest => dest.LineItems, opt => opt.Ignore())  // Added separately
            .ForMember(dest => dest.DependentCosts, opt => opt.Ignore())  // Added separately
            .ForMember(dest => dest.AdvanceVATs, opt => opt.Ignore())  // Added separately
            .ForMember(dest => dest.BrojDokumentaINT, opt => opt.Ignore())
            .ForMember(dest => dest.Godina, opt => opt.Ignore())
            .ForMember(dest => dest.IDInterniPartner, opt => opt.Ignore())
            .ForMember(dest => dest.NapomenaSystem, opt => opt.Ignore())
            .ForMember(dest => dest.UserName, opt => opt.Ignore())
            .ForMember(dest => dest.UserLokacija, opt => opt.Ignore())
            .ForMember(dest => dest.UserDatum, opt => opt.Ignore())
            .ForMember(dest => dest.IDNacinPlacanja, opt => opt.Ignore())
            .ForMember(dest => dest.ObracunAkciza, opt => opt.Ignore())
            .ForMember(dest => dest.ObracunPorez, opt => opt.Ignore())
            .ForMember(dest => dest.ObracunPorezPomocni, opt => opt.Ignore())
            .ForMember(dest => dest.AvansIznos, opt => opt.Ignore())
            .ForMember(dest => dest.IDModelKontiranja, opt => opt.Ignore())
            .ForMember(dest => dest.IDMestoIsporuke, opt => opt.Ignore())
            .ForMember(dest => dest.TrebovanjeIDArtikal, opt => opt.Ignore())
            .ForMember(dest => dest.TrebovanjeKolicina, opt => opt.Ignore())
            .ForMember(dest => dest.IznosPrevaranti, opt => opt.Ignore())
            .ForMember(dest => dest.IDTroskovnoMesto, opt => opt.Ignore())
            .ForMember(dest => dest.IDVozac, opt => opt.Ignore())
            .ForMember(dest => dest.IDVozilo, opt => opt.Ignore())
            .ForMember(dest => dest.IDLinijaProizvodnje, opt => opt.Ignore())
            .ForMember(dest => dest.IDSvrhaInternihRacuna, opt => opt.Ignore())
            .ForMember(dest => dest.UserNameK, opt => opt.Ignore())
            .ForMember(dest => dest.UserLokacijaK, opt => opt.Ignore())
            .ForMember(dest => dest.UserDatumK, opt => opt.Ignore())
            .ForMember(dest => dest.Bruto, opt => opt.Ignore())
            .ForMember(dest => dest.Neto, opt => opt.Ignore())
            .ForMember(dest => dest.GranicniPrelaz, opt => opt.Ignore())
            .ForMember(dest => dest.IDStorniranogDokumenta, opt => opt.Ignore())
            .ForMember(dest => dest.IDUlazniRacuniOsnovni, opt => opt.Ignore())
            .ForMember(dest => dest.IznosCek, opt => opt.Ignore())
            .ForMember(dest => dest.IznosKartica, opt => opt.Ignore())
            .ForMember(dest => dest.IznosGotovina, opt => opt.Ignore())
            .ForMember(dest => dest.BrojPutnogNaloga, opt => opt.Ignore())
            .ForMember(dest => dest.Otpremljeno, opt => opt.Ignore())
            .ForMember(dest => dest.VremeRazvoza, opt => opt.Ignore())
            .ForMember(dest => dest.BrojDokAlt, opt => opt.Ignore())
            .ForMember(dest => dest.Napomena2, opt => opt.Ignore())
            .ForMember(dest => dest.Napomena3, opt => opt.Ignore())
            .ForMember(dest => dest.SinhronizovanAccess, opt => opt.Ignore())
            .ForMember(dest => dest.Feler, opt => opt.Ignore())
            .ForMember(dest => dest.IndikatorNaknadnogOdobrenja, opt => opt.Ignore())
            .ForMember(dest => dest.OdobrioNaknadnuIsporuku, opt => opt.Ignore())
            .ForMember(dest => dest.ImePrezimeMetro, opt => opt.Ignore())
            .ForMember(dest => dest.BrojNarudzbenice, opt => opt.Ignore())
            .ForMember(dest => dest.BrojProdavnice, opt => opt.Ignore())
            .ForMember(dest => dest.DatumNarudzbenice, opt => opt.Ignore())
            .ForMember(dest => dest.IDTekuciRacun, opt => opt.Ignore())
            .ForMember(dest => dest.PozivNaBroj, opt => opt.Ignore())
            .ForMember(dest => dest.VrednostSaRacuna, opt => opt.Ignore())
            .ForMember(dest => dest.PozivNaBroj1, opt => opt.Ignore())
            .ForMember(dest => dest.Rok, opt => opt.Ignore())
            .ForMember(dest => dest.Kilometraza, opt => opt.Ignore())
            .ForMember(dest => dest.Kontakt, opt => opt.Ignore())
            .ForMember(dest => dest.Registracija, opt => opt.Ignore())
            .ForMember(dest => dest.IDRadnik2, opt => opt.Ignore())
            .ForMember(dest => dest.DodatniRadoviIznos, opt => opt.Ignore())
            .ForMember(dest => dest.IDPartner2, opt => opt.Ignore())
            .ForMember(dest => dest.ZakljucanDokument, opt => opt.Ignore())
            .ForMember(dest => dest.IDVrstaTroska, opt => opt.Ignore())
            .ForMember(dest => dest.IDPrikolica, opt => opt.Ignore())
            .ForMember(dest => dest.IDMesto1, opt => opt.Ignore())
            .ForMember(dest => dest.IDMesto2, opt => opt.Ignore())
            .ForMember(dest => dest.IDMerenje, opt => opt.Ignore());

        // UpdateDocumentDto -> Document Entity (for updates)
        CreateMap<UpdateDocumentDto, Document>()
            .ForMember(dest => dest.IDDokument, opt => opt.Ignore())
            .ForMember(dest => dest.BrojDokumenta, opt => opt.MapFrom(src => src.DocumentNumber))
            .ForMember(dest => dest.Datum, opt => opt.MapFrom(src => src.DocumentDate))
            .ForMember(dest => dest.IDPartner, opt => opt.MapFrom(src => src.PartnerId))
            .ForMember(dest => dest.IDOrganizacionaJedinica, opt => opt.MapFrom(src => src.OrganizationalUnitId))
            .ForMember(dest => dest.IDReferentniDokument, opt => opt.MapFrom(src => src.ReferentDocumentId))
            .ForMember(dest => dest.ZavisniTroskoviBezPDVa, opt => opt.MapFrom(src => src.DependentCostsNet))
            .ForMember(dest => dest.ZavisniTroskoviPDV, opt => opt.MapFrom(src => src.DependentCostsVat))
            .ForMember(dest => dest.Napomena, opt => opt.MapFrom(src => src.Note))
            .ForMember(dest => dest.ObradjenDokument, opt => opt.MapFrom(src => src.Processed))
            .ForMember(dest => dest.ProknjizenDokument, opt => opt.MapFrom(src => src.Posted))
            .ForMember(dest => dest.DokumentTimeStamp, opt => opt.Ignore())
            .ForMember(dest => dest.LineItems, opt => opt.Ignore())
            .ForMember(dest => dest.DependentCosts, opt => opt.Ignore())
            .ForMember(dest => dest.AdvanceVATs, opt => opt.Ignore());
    }
}
